spring:
  application:
    name: wavit
  profiles:
    group:
      test: test
      local: local, datasource
      prod: prod, datasource
    include:
      - actuator
      - security
    active: ${SPRING_PROFILES_ACTIVE:local}
