management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /wavit-actuator
    jmx:
      exposure:
        exclude: "*"
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
