spring:
  config:
    activate:
      on-profile: "storage"

storage:
  accessKey: ${AWS_ACCESS_KEY_ID:}
  secretKey: ${AWS_SECRET_ACCESS_KEY:}
  bucket: ${AWS_S3_BUCKET_NAME:}
  region: ${AWS_REGION:}
