spring:
  application:
    name: wavit
  profiles:
    group:
      test: test
      local: local, datasource
      prod: prod, datasource
    include:
      - storage
      - actuator
      - security
    active: ${SPRING_PROFILES_ACTIVE:local}

logging:
  level:
    xyz.wavit.domain.*.api.*: debug
    org.springframework.web: debug
    org.springframework.orm.jpa: debug
    org.springframework.transaction: debug
